Create GOVERNANCE.md
kaijagahm/R-help-reprexes pull request #40
Opened 2024-08-22 03:31 UTC by kaijagahm

Adapted [Governance document from the CLDT repository](https://github.com/carpentries/lesson-development-training/blob/main/GOVERNANCE.md#meeting-agenda)--refer back to it to see what I changed.

Notably, instead of having the responsibility of scheduling/leading meetings rest entirely with the Lead Maintainer (me, for now), I noted that we want that responsibility to rotate. I left most of the notes about the notetaker/timekeeper as they were in the original doc. I did not set any particular schedule for Maintainer meetings, or any particular process for others to join. I foresee us updating this governance doc if/when the project moves beyond this initial drafting stage and into a stage where we are more regularly inviting feedback from other people--we're not there yet, as we discussed today, and we won't be adding people right now.

@xortizross and @peterlaurin please read this over and make sure you agree with what I've written, and/or suggest changes if you like! This is a draft. I want us all to agree on it before finalizing it, so I'm explicitly requiring review from both of you, not just one.

2024-08-22 14:16 UTC, xortizross requested changes
This is awesome Kaija, thank you! Just a few notes below.

Line 69: it says we meet at minimum 4 times a year but earlier we said twice monthly. I'm not sure if this is intentional or accidental, and either way a tad confusing.

Line 89: I think we should call the “project Google Doc” the “Lesson Development doc” and keep that consistent moving forward, maybe even formalize a draft of it in the repo? Dunno, maybe once we finish the main build. 

Line 126: I don’t know that decisions need to be recorded as an issue at this stage, we are making many decisions, maybe they can just be added to the meeting notes as, for example, “discussion on x  decision to be made. Update: the decision Y was made outside of the meeting by consensus”.  Then issues can be created as needed.

2024-08-29 21:24 UTC, kaijagahm reviewed
Made these changes! Thanks.

2024-08-29 21:25 UTC, xortizross approved these changes

2024-08-29 21:25 UTC, merged

2024-08-29 21:27 UTC, kaijagahm commented
Closes #40